### ISSUE TITLE
how to disable binddn and bindpwd parameters? It doesn't apply to my ldap structure

### ISSUE THREAD

**Issue by juanlet** [XavRsl/Ldap#8]
I tried to comment these two fields and I couldn't make it work cause it says Undefined index: binddn. I need a way to use it without admin authentication. Any ideas?

/*
    |--------------------------------------------------------------------------
    | LDAP ADMIN bind DN
    |--------------------------------------------------------------------------
    */

```
'binddn' => env('LDAP_BIND_DN', 'cn=Manager,dc=domain,dc=fr'),

/*
|--------------------------------------------------------------------------
| LDAP ADMIN bind password
|--------------------------------------------------------------------------
|
*/
'bindpwd' => env('LDAP_BIND_PASSWORD'),
```

**Comment by juanlet** [comment]
I solved it by using and it works perfectly....

```
|--------------------------------------------------------------------------
| LDAP ADMIN bind DN
|--------------------------------------------------------------------------
*/

'binddn' => env('LDAP_BIND_DN', null),

/*
|--------------------------------------------------------------------------
| LDAP ADMIN bind password
|--------------------------------------------------------------------------
|
*/
'bindpwd' => env('LDAP_BIND_PASSWORD', null),
```

**Comment by XavRsl** [comment]
You should put the null values in your .env file :
LDAP_BIND_DN=null
LDAP_BIND_PASSWORD=null
So you don't need to edit the config file.

Xavier
